### ISSUE TITLE
Error In demo

### ISSUE THREAD

**Issue by Gautamshahi** [BorderCloud/sgvizler2#17]
Why i am getting the below error?

Sorry, the sparql server sent an error. 
You need to allow running insecure content in your navigator or this SPARQL service doesn't exist or timed out or CORS violation or no Access-Control-Allow-Origin header set. (see console log)

![image](https://user-images.githubusercontent.com/3966230/34616461-55b77296-f25e-11e7-9ed9-b78ca288a9f7.png)

**Comment by BorderCloud** [comment]
You need to allow running insecure content in your navigator.
Click on this icon in your navigator and you need to allow running insecure content.
![34616461-55b77296-f25e-11e7-9ed9-b78ca288a9f7](https://user-images.githubusercontent.com/352813/34618211-526def90-f23e-11e7-9842-06e3335ab9bb.png)

**Comment by Gautamshahi** [comment]
Thank you. When I am trying to represent data on Map, The following error occurred. I also tried by providing decimal value of latitude and longitude. Please suggest the possible solution.

![image](https://user-images.githubusercontent.com/3966230/34656263-24070884-f43d-11e7-9481-28ad0e250cb6.png)

**Comment by BorderCloud** [comment]
You need to convert the type for the chart
For example :  (xsd:decimal(?latitude) as ?lat)

**Comment by Gautamshahi** [comment]
Hi,
Thank you.

My RDF code is (part of it)
 dm:Patna  a           owl:NamedIndividual <http://drtc.isibang.ac.in/ontology/dm/#city> ;
        dm:latitude   13.067439 ;
        dm:longitude  80.237617 ;
        dm:occuredIn  dm:Patna .

I am using the below SPARQL code on Sgvizler demo platform is
SELECT ?occuredIn  ?Lat ?Long 
	WHERE {  ?x dm:occuredIn ?occuredIn .
                                          ?x dm:latitude ?latitude .
                                       ?x dm:longitude  ?longitude  .
                                     BIND(xsd:decimal(?latitude) AS ?Lat).
                                     BIND(xsd:decimal(?longitude) AS ?Long) .                             
}  

Again, I am getting the same error. 

Will you please elaborate it?  Where am I doing wrong?

Thanks in Advance.

**Comment by BorderCloud** [comment]
You don't respect the order of columns.

Column | Type | Description
0 | Number | Latitude
1 | Number | Longitude
2 | string (Optional) | Title of popup or simple label or HTML
3 | string (Optional) | Description in the popup
4 | string (Optional) |  
5 | url (Optional) | Link of title
6 | url (Optional) | Image in the popup
