### ISSUE TITLE
Problem With locating Lat & Long on Map 

### ISSUE THREAD

**Issue by Gautamshahi** [BorderCloud/sgvizler2#18]
I am trying to represent the result of SPARQL Query in Map. I fed the data (longitude and latitude) in decimal format. I am getting the below error (image) while trying leaflet.visualization and no result in the case of google.visualization.
![image](https://user-images.githubusercontent.com/3966230/34701469-661f3cf6-f50e-11e7-8ac5-ef4d661eb383.png)

I tried a similar query for Wiki-data but I am getting the desired output on Map.

I tried with type conversion using BIND but still getting the same error.

Please help me to locate the latitude and longitude on Map.

**Comment by BorderCloud** [comment]
You don't respect the order of columns. 

Column | Type | Description
0 | Number | Latitude
1 | Number | Longitude
2 | string (Optional) | Title of popup or simple label or HTML
3 | string (Optional) | Description in the popup
4 | string (Optional) |  
5 | url (Optional) | Link of title
6 | url (Optional) | Image in the popup
