### ISSUE TITLE
Can we run the editor of sgvizler2 on my local machine?

### ISSUE THREAD

**Issue by Gautamshahi** [BorderCloud/sgvizler2#21]
Hi,

I wanted to run the editor of sgvizler2 like https://bordercloud.github.io/sgvizler2/tutorial-A_Editor.html in my local machine.

Can you please share the instructions?

**Comment by BorderCloud** [comment]
In resume :
```
# 1. Start the Web server
yarn dev:httpd

# 2. Build all
yarn clean
yarn docs:all
```
After, you can open the editor with this link : http://localhost:8000

[The doc is here](https://github.com/BorderCloud/sgvizler2/blob/master/DEVELOPMENT.md)
